brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    todo_item_create,
    todo_item_update,
    todo_list_create,
    todo_list_delete,
    todo_list_detail,
    todo_list_list,
    todo_list_update,
)


urlpatterns = [
    path("", todo_list_list, name="todo_list_list"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create, name="todo_list_create"),
    path("<int:id>/edit/", todo_list_update, name="todo_list_update"),
    path("<int:id>/delete/", todo_list_delete, name="todo_list_delete"),
    path("items/create/", todo_item_create, name="todo_item_create"),
    path("items/<int:id>/edit/", todo_item_update, name="todo_item_update"),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

todos/forms.py
from django.forms import ModelForm
from todos.models import TodoItem, TodoList


class TodoListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = "__all__"


class TodoItemForm(ModelForm):
    class Meta:
        model = TodoItem
        fields = "__all__"

todos/views.py
from django.shortcuts import render, redirect

from todos.models import TodoItem, TodoList
from todos.forms import TodoItemForm, TodoListForm


def todo_list_list(request):
    lists = TodoList.objects.all()
    context = {
        "lists": lists,
    }
    return render(request, "todos/todo_list.html", context)


def todo_list_detail(request, id):
    list = TodoList.objects.get(id=id)
    context = {
        "list": list,
    }
    return render(request, "todos/todo_list_detail.html", context)


def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            list = form.save()
            return redirect("todo_list_detail", id=list.id)
    else:
        form = TodoListForm()
    context = {
        "form": form,
    }
    return render(request, "todos/todo_list_create.html", context)


def todo_list_update(request, id):
    list = TodoList.objects.get(id=id)
    if request.method == "POST":
        form = TodoListForm(request.POST, instance=list)
        if form.is_valid():
            list = form.save()
            return redirect("todo_list_detail", id=list.id)
    else:
        form = TodoListForm(instance=list)
    context = {
        "form": form,
    }
    return render(request, "todos/todo_list_update.html", context)


def todo_list_delete(request, id):
    if request.method == "POST":
        list = TodoList.objects.get(id=id)
        list.delete()
        return redirect("todo_list_list")
    return render(request, "todos/todo_list_delete.html")


def todo_item_create(request):
    if request.method == "POST":
        form = TodoItemForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect("todo_list_detail", id=item.list.id)
    else:
        form = TodoItemForm()
    context = {
        "form": form,
    }
    return render(request, "todos/todo_item_create.html", context)


def todo_item_update(request, id):
    item = TodoItem.objects.get(id=id)
    if request.method == "POST":
        form = TodoItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save()
            return redirect("todo_list_detail", id=item.list.id)
    else:
        form = TodoItemForm(instance=item)
    context = {
        "form": form,
    }
    return render(request, "todos/todo_item_update.html", context)

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>

todos/templates/todos/todo_item_create.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Create a New Item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% comment %} <p>
                <label for="id_task">Task:</label>
                <input type="text" id="id_task" name="task" required>
                </p>
                <p>
                <label for="id_due_date">Due Date:</label>
                <input type="text" id="id_due_date" name="due_date" >
                </p>
                <p>
                <label for="id_is_completed">Completed:</label>
                <input type="checkbox" id="id_is_completed" name="is_completed">
                </p>
                <p>
                <label for="id_list">List:</label>
                <select id="id_list" name="list" required>
                    <option value="" disabled selected>Select a list</option>
                    {% for todo_list in todo_lists %}
                        <option value="{{ todo_list.id }}">{{ todo_list.name }}</option>
                    {% endfor %}
                </p>
                </select> {% endcomment %}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
    {% endblock content %}

todos/templates/todos/todo_item_update.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% comment %} <p>
                    <label for="id_task">Task:</label>
                    <input type="text" id="id_task" name="task" value="{{ form.instance.task }}" required>
                </p>
                <p>
                    <label for="id_due_date">Due Date:</label>
                    <input type="text" id="id_due_date" name="due_date" value="{{ form.instance.due_date }}" placeholder="YYYY-MM-DD">
                </p>
                <p>
                    <label for="id_is_completed">Completed:</label>
                    <input type="checkbox" id="id_is_completed" name="is_completed" {% if form.instance.is_completed %}checked{% endif %}>
                </p>
                <p>
                    <label for="id_list">List:</label>
                    <select id="id_list" name="list" required >
                        {% comment %} <option value="" disabled selected>Select a list</option>
                        {% for todo_list in todo_lists %}
                            <option value="{{ todo_list.id }}">{{ todo_list.name }}</option>
                        {% endfor %} {% endcomment %}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
    {% endblock content %}

todos/templates/todos/todo_list.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div>
      <h1>My Lists</h1>
      <p>
        <a href="{% url 'todo_list_create' %}">Create a new todo list</a>
      </p>
      <p>
        <a href="{% url 'todo_item_create' %}">Create a new item</a>
      </p>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Number of items</th>
            <th>Created On</th>
          </tr>
        </thead>
        <tbody>
          {% for list in lists %}
            <tr>
              <td>
                <a href="{% url 'todo_list_detail' list.id %}">{{ list.name }}</a>
              </td>
              <td>{{ list.items.all|length }}</td>
              <td>{{ list.created_on }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
{% endblock content %}

todos/templates/todos/todo_list_create.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div>
      <h1>Create a new list</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
      </form>
    </div>
  </main>
{% endblock content %}






{% comment %} def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            new_todo_list = form.save()
            return redirect("todos:todo_list_detail", id=new_todo_list.id)
    else:
        form = TodoListForm()
    return render(request, "todos/todo_list_create.html", {"form": form}) {% endcomment %}

todos/templates/todos/todo_list_delete.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div>
      <h1>Are you sure?</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Delete</button>
      </form>
    </div>
  </main>
{% endblock content %}

todos/templates/todos/todo_list_detail.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div>
      <h1>{{ list.name }}</h1>
      <p>
        <a href="{% url 'todo_list_update' list.id %}">Edit</a>
      </p>
      <p>
        <a href="{% url 'todo_list_delete' list.id %}">Delete</a>
      </p>
      <h2>Tasks</h2>
      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Due date</th>
          </tr>
        </thead>
        <tbody>
          {% for item in list.items.all %}
            <tr>
              <td>
                <a href="{% url 'todo_item_update' item.id %}">{{ item.task }}</a>
              </td>
              <td>{{ item.due_date|date:"M d, Y" }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
{% endblock content %}

todos/templates/todos/todo_list_update.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div>
      <h1>Update list</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Update</button>
      </form>
    </div>
  </main>
{% endblock content %}